#!/usr/bin/env node
// Keeps the crawlable parts of index.html in lockstep with the React
// content modules. Runs as `prebuild` (and can be run by hand):
//
//   1. FAQPage JSON-LD  <- src/content/faq.js      (Google requires visible parity)
//   2. <noscript> block <- src/content/services.js + faq.js
//
// 3. <noscript> also mirrors src/content/work.js + about.js (homepage work lists, about copy)
// 4. src/content/site-links.js <- src/pages (scripts/site-links.mjs): the pages the homepage links to
//
// The site is a client-rendered SPA, so crawlers that don't execute JS
// (many AI fetchers, and Bing less reliably) only read the raw HTML. The
// <noscript> mirror gives them the same ~1,000 words a browser user sees,
// instead of a two-line stub.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { workItems, projects } from '../src/content/work.js';
import { aboutText, aboutTitle, processSteps } from '../src/content/about.js';
import { dirname, resolve } from 'node:path';
import { siteLinks } from './site-links.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { faq } = await import(resolve(root, 'src/content/faq.js'));
const { services, servicesIntro } = await import(resolve(root, 'src/content/services.js'));

const htmlPath = resolve(root, 'index.html');
let html = readFileSync(htmlPath, 'utf8');

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// ---- 1. FAQPage node inside the @graph ---------------------------------
const ldStart = html.indexOf('<script type="application/ld+json">');
const ldEnd = html.indexOf('</script>', ldStart);
const ldOpen = html.indexOf('>', ldStart) + 1;
const graph = JSON.parse(html.slice(ldOpen, ldEnd));
const faqNode = graph['@graph'].find((n) => n['@type'] === 'FAQPage');
if (!faqNode) throw new Error('FAQPage node not found in index.html JSON-LD');
faqNode.mainEntity = faq.map(({ q, a }) => ({
    '@type': 'Question',
    name: q,
    acceptedAnswer: { '@type': 'Answer', text: a },
}));
const ldBody = '\n  ' + JSON.stringify(graph, null, 2).replace(/\n/g, '\n  ') + '\n  ';
html = html.slice(0, ldOpen) + ldBody + html.slice(ldEnd);

// ---- 4. the pages the homepage links to --------------------------------
const links = await siteLinks(root);
writeFileSync(
    resolve(root, 'src/content/site-links.js'),
    '// Generated by scripts/sync-static.mjs from src/pages (scripts/site-links.mjs) — do not edit by hand.\n'
        + `export const siteLinks = ${JSON.stringify(links, null, 4)};\n`,
);

// ---- 2. <noscript> mirror ---------------------------------------------
const noscript = `<noscript>
    <h1>David Geha - AI Consultant in Lebanon</h1>
    <p>David Geha is an independent AI consultant in Lebanon offering AI consulting, AI automation and AI
      agents, AI for SEO and GEO, AI outreach systems and custom AI solutions for marketing agencies, F&amp;B
      businesses and founders in Beirut and across Lebanon.</p>

    <h2>AI consulting &amp; AI solutions in Lebanon</h2>
    <p>${esc(servicesIntro)}</p>
${services.map(({ title, text }) => `    <h3>${esc(title)}</h3>\n    <p>${esc(text)}</p>`).join('\n')}

    <h2>Selected work</h2>
    <ul>
${projects.map(({ title, category, year }) => `      <li>${esc(title)} — ${esc(category)}, ${esc(year)}</li>`).join('\n')}
    </ul>

    <h2>Recent work</h2>
    <ul>
${workItems.map(({ date, title, tags }) => `      <li><strong>${esc(date)}</strong> — ${esc(title)} (${esc(tags.join(', '))})</li>`).join('\n')}
    </ul>

    <h2>${esc(aboutTitle)}</h2>
    <p>${esc(aboutText)} <a href="/about/">More about David</a>.</p>
    <ol>
${processSteps.map(({ num, label }) => `      <li>${esc(num)} — ${esc(label)}</li>`).join('\n')}
    </ol>

    <h2>Working with an AI consultant in Lebanon</h2>
${faq.map(({ q, a }) => `    <h3>${esc(q)}</h3>\n    <p>${esc(a)}</p>`).join('\n')}

    <h2>Pages</h2>
    <ul>
      <li><a href="/ai-consulting-lebanon/">AI consulting in Lebanon</a></li>
      <li><a href="/ai-solutions-lebanon/">AI solutions &amp; automation for businesses in Lebanon</a></li>
${links.pages.map(({ href, label }) => `      <li><a href="${href}">${esc(label)}</a></li>`).join('\n')}${links.pages.length ? '\n' : ''}${links.hub ? '      <li><a href="/blog/">All guides</a></li>\n' : ''}${links.articles.map(({ href, title }) => `      <li><a href="${href}">${esc(title)}</a></li>`).join('\n')}${links.articles.length ? '\n' : ''}${links.work ? '      <li><a href="/work/">Case studies</a></li>\n' : ''}      <li><a href="/about/">About David Geha</a></li>
    </ul>

    <p>Contact: <a href="mailto:david@osgdev.com">david@osgdev.com</a> ·
      <a href="tel:+96176412978">+961 76 412 978</a> (WhatsApp) · Beirut, Lebanon ·
      <a href="https://www.linkedin.com/in/david-geha/">LinkedIn</a> ·
      <a href="https://github.com/Daveisgm05">GitHub</a> ·
      <a href="https://www.instagram.com/dave.automates/">Instagram</a></p>
  </noscript>`;

const nsStart = html.indexOf('<noscript>\n    <h1>');
const nsEnd = html.indexOf('</noscript>', nsStart) + '</noscript>'.length;
if (nsStart < 0) throw new Error('crawl-fallback <noscript> block not found in index.html');
html = html.slice(0, nsStart) + noscript + html.slice(nsEnd);

writeFileSync(htmlPath, html);
console.log(`sync-static: ${faq.length} FAQ items → JSON-LD, ${services.length} services + ${faq.length} FAQs → <noscript>`);
