// Generated by scripts/sync-static.mjs from src/pages (scripts/site-links.mjs) — do not edit by hand.
export const siteLinks = {
    "guide": {
        "href": "/blog/ai-consulting-in-lebanon-guide/",
        "label": "Guide"
    },
    "hub": null,
    "articles": [
        {
            "href": "/blog/ai-consulting-in-lebanon-guide/",
            "label": "2026 guide: costs & how to choose",
            "title": "AI Consulting in Lebanon: the 2026 guide to costs, firms and how to choose"
        }
    ],
    "pages": [
        {
            "href": "/ai-agents-lebanon/",
            "label": "AI agents"
        },
        {
            "href": "/ai-automation-lebanon/",
            "label": "AI automation"
        },
        {
            "href": "/ai-outreach-lebanon/",
            "label": "AI outreach systems"
        },
        {
            "href": "/ai-seo-geo-lebanon/",
            "label": "AI for SEO & GEO"
        },
        {
            "href": "/privacy/",
            "label": "Privacy"
        }
    ],
    "work": null
};
