// Generated by scripts/sync-static.mjs from src/pages (scripts/site-links.mjs) — do not edit by hand.
export const siteLinks = {
    "guide": {
        "href": "/blog/ai-consulting-in-lebanon-guide/",
        "label": "Guide"
    },
    "hub": null,
    "articles": [
        {
            "href": "/blog/ai-consulting-in-lebanon-guide/",
            "label": "2026 guide: costs & how to choose",
            "title": "AI Consulting in Lebanon: the 2026 guide to costs, firms and how to choose"
        }
    ],
    "pages": [],
    "work": null
};
