import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve, dirname, join, relative } from 'node:path'
import { readdirSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))

// Static content pages are generated by scripts/build-pages.mjs (prebuild /
// predev) into <slug>/index.html with a `.generated` marker. Every one of
// them becomes its own HTML entry so Vite emits dist/<slug>/index.html.
function generatedPages(dir = root, out = {}) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory() || ['node_modules', 'dist', 'public', 'src', '.git', 'scripts'].includes(entry.name)) continue
    const full = join(dir, entry.name)
    if (existsSync(join(full, '.generated'))) out[relative(root, full)] = join(full, 'index.html')
    generatedPages(full, out)
  }
  return out
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  build: {
    rollupOptions: {
      input: { main: resolve(root, 'index.html'), ...generatedPages() },
    },
  },
})
